robsontenorio/mary

src/View/Components/Choices.php, src/View/Components/Main.php
=> Choices/Main: uses `overflow-y-auto` instead.

src/View/Components/Select.php
Edited: `src/View/Components/Select.php`
This PR aims to improve the UI consistency by adding pt-0 to the select input label. The modification aligns the select box with text input elements.
Added pt-0 for consistency, making sure that the select input labels are aligned with text input labels across components.
Without `pt-0`:
With the fix:
=> fix: added pt-0 to select label

src/View/Components/Table.php
=> Table: add `no-headers` attribute.

src/View/Components/Dropdown.php, src/View/Components/Header.php, src/View/Components/Input.php, src/View/Components/MenuItem.php, src/View/Components/Select.php
**Header**: primary color for progress indicator , default color for dark.
**Input**: primary color for border at prefix/suffix 
**Dropbox**: hide caret summary icon
**Select**: better inline label background for dark,  "clickable" inline label, "clickable" icons.
**Input**: better inline label background for dark, bind label to field input,  "clickable" icons.
=> CSS: improve some components

src/MaryServiceProvider.php
Fixes #117 
Also register as <x-icon> if there is a prefix for Mary components.
=> Fix: component prefix for icons.

src/View/Components/Modal.php
**Description:**
In this PR, we have made significant changes to the Modal component. The modal is now designed to close by default when a user clicks outside or ESC key.
**New Feature:**
- We have introduced a new `persistent` prop. By default, the modal can be closed by clicking outside or pressing the ESC key. If you want to prevent this default closure behavior, you can use the `persistent` prop.
**Usage Example:**
```blade
<x-modal wire:model="myModal" persistent>
```
**Note:** _The author is welcome to make further adjustments or improvements to this code as needed. Feel free to modify the code to better._
=> Include Close on Outside Click for Modal Component (Enabled by Default)

src/View/Components/ListItem.php
- Avoid to render avatar div, if explicitly not used, for better spacing.
=> ListItem: omit avatar if not used

src/MaryServiceProvider.php, src/View/Components/Alert.php, src/View/Components/Button.php, src/View/Components/Choices.php, src/View/Components/DatePicker.php, src/View/Components/DateTime.php, src/View/Components/Dropdown.php, src/View/Components/Input.php, src/View/Components/Main.php, src/View/Components/Menu.php, src/View/Components/MenuItem.php, src/View/Components/MenuSeparator.php, src/View/Components/MenuSub.php, src/View/Components/Modal.php, src/View/Components/Select.php, src/View/Components/Stat.php, src/View/Components/Tab.php, src/View/Components/Table.php
Fix #117 
No matter if components has custom prefix or not, we also register these alias to avoid naming collision, because they are used inside some Mary's components itself.
=> Fix component prefix

src/Traits/Toast.php, src/View/Components/Toast.php
Fixes #148 #149 
- Allow html within `title` and `description`
- Enable default icons
- Allow custom icons
<br><br><br>
<hr />
<hr />
<hr />
<br><br><br>
=> Toast: improvements

src/View/Components/Button.php
Fix a case where `link` has HTML entity like `/user?param=1&param=2`
=> Button: fix link with HTML entity

src/View/Components/Button.php
- Fix an issue when button have a `icon` + `spinner`  and error is thrown (default Livewire error modal), then icon disappear.
- Allow spinner for right icon.
=> Button: better spinner handling

src/View/Components/MenuItem.php
If you want a menu item act as regular link.
Useful on '/logout' action, in order to make proper redirects from Laravel.
=> MenuItem: add `no-wire-navigate`

src/MaryServiceProvider.php, src/View/Components/Drawer.php
Now `x-drawer` has `x-card` embed inside itself.
New `x-drawer` attributes:
- title
- subtitle
- with-close-button
- separator
New slot:
- actions
=> Drawer: embeds `x-card`

src/View/Components/Input.php
Fix #180 
- Fix an issue when input has no `wire:model` associated and a validation error happens in another input.
=> Input: fix validation

src/View/Components/Input.php
Fix #172 
- Fix weird issue when `x-ref` is placed but not used.
=> Input: fix `x-ref` if not using `money`

src/View/Components/Table.php
Fix #171 
Fix `select all` when `rows` is paginated.
=> Table: fix `selectable` for pagination

src/View/Components/Choices.php
Fix #191  #188 
- Add `selection` slot.
- Allow `wire:model.live`.
- Fix issue when key value starts with ZERO.
=> Choices: improvements

src/View/Components/Header.php
The header component generates two double quotes at the end of the attributes:
After the change in this PR:
=> Fix double quote in header component

src/View/Components/Button.php, src/View/Components/Stat.php, src/View/Components/Toast.php
When using multiple buttons as group, using daisyUI's [Join Component](https://daisyui.com/components/join/) I found an issue where the last button doesn't have a rounded border.
After checking the code I came to the conclusion this was caused because of the hidden `span` that was added after the button. As last element in the Join Component the `span` got the rounded border.
As far as I could find (and suggested by the comment) this `span` in the `Button` and `Stat` component is only used for the builder, because the classes of the `span` are not anywhere else in the code. Tailwind advises againt the use of [dynamic class names](https://tailwindcss.com/docs/content-configuration#dynamic-class-names).
For the `Button` and `Stat` component this is a straight forward fix, because the …
=> Fix tailwind force, remove dynamic class names

src/MaryServiceProvider.php
Add ability to inject extra external variables 
```php
public string $some =  'Hello';
public int $other = 12;
```
Just pass then as additional variables.
```html
<x-choices ...>
@scope('item', $user, $some, $other)
...
@endscope
</x-choices>
```
At this time `@scope` are available  on `<x-table>` and `<x-choices>` custom slots.
=> Scope: allow external variables

src/View/Components/DatePicker.php
Fix a weird input duplication when using `wire:navigate` and click browse back button.
=> DatePicker: fix `wire:navigate` back

src/View/Components/Choices.php, src/View/Components/ChoicesOffline.php, src/View/Components/Tags.php
Fix a weird element duplication when using wire:navigate and click browse back button.
- Choices
- ChoicesOffline
- Tags
=> Choices/ChoicesOffline/Tags: fix `wire:navigate` back

src/View/Components/Choices.php, src/View/Components/ChoicesOffline.php, src/View/Components/DatePicker.php, src/View/Components/DateTime.php, src/View/Components/Input.php, src/View/Components/Radio.php, src/View/Components/Select.php, src/View/Components/Tags.php, src/View/Components/Textarea.php
Fixed a bug where the asterisk (*) was always shown, ignoring the "required" attribute boolean value.
```php
<x-input :required="false" label="Name" wire:model="name" />
```
```php
<x-input :required="false" label="Name" wire:model="name" />
```
```php
<x-input :required="true" label="Name" wire:model="name" />
```
```php
<x-input required label="Name" wire:model="name" />
```
=> Ignore displaying asterisk when "required" is false

src/View/Components/Input.php
Fix a case when is used with modifiers like `wire:model.live.debounce`
=> Input: fix `clearable` for `live` modifiers

src/View/Components/Input.php
Fix #242 
Support models arrays. Ex: wire:model="emails.0"  , wire:model="emails.1"
=> Input: fix array models

src/View/Components/Tags.php
Fix #239 
Fix case where uses `live`
=> Tags: fix `wire:model.live`

src/View/Components/Select.php
Fix #242 
Support models arrays. Ex: wire:model="emails.0" , wire:model="emails.1"
=> Select: fix array model

src/View/Components/ThemeToggle.php
HI i used the new compoent and sow that the checkbox under the theme icon was still visible, so i put an opacity-0 proprerty to the chckbox
=> Adding opacity 0 to checkbox in theme toggle

src/View/Components/Drawer.php
Fix tabindex when drawer is hidden on right side and contains input fields.
=> Drawer: add `x-trap.inert`

src/View/Components/Table.php
- Allow to access the `$loop` context.
- Add row and cell decoration properties.
How to test
```zsh
composer require robsontenorio/mary:dev-table-loopcontext
php artisan view:clear.
```
=> Table: loop and decoration

src/View/Components/Choices.php, src/View/Components/ChoicesOffline.php
It would be good if the choices component issued an on change event similar to other inputs and selects. I added the capability for the user to use their own @change directive on the component. This is passed into the $attributes iterable and there is an added function called onChangeFunc that will return the value passed. Then, in the html rendered, onChange is set up in x-data as an anonymous function that wraps around the passed value. This protects the other rendered code. When toggle is called, the onchange function is triggered. The anonymous function is passed the value of selection and this is exposed to the user as a $value variable, which they can do cool stuff with, like emit an event or something. This has been tested in both single and multi choice components. It works well …
=> Choices: add `@change-selection` event

src/View/Components/File.php
This PR aims to highlight the * in red when the x-file field is required, following the mary ui form pattern.
=> Enhancement: add * when required to x-file component

src/View/Components/Main.php
This PR aims to enable users to specify a different icon for the collapsible option when using the Main component.
=> enhancement: add custom icon to main component

src/View/Components/Table.php
Better spacing when using `link` property or `action` slot.
=> Table: Improve spacing CSS

src/View/Components/Header.php
Do not render `middle` slot if not used.
=> Header: omit `middle` slot if not used

src/View/Components/Choices.php, src/View/Components/ChoicesOffline.php
Fix #321 Fix #320
- **Choices**: Support `disabled` state.
- **ChoicesOffline**: Add `x-cloak` to prevent list flashing.
```sh
composer require robsontenorio/mary:dev-choices-disabled
php artisan view:clear
```
=> Choices: fixes + improvements

src/MaryServiceProvider.php, src/View/Components/Accordion.php, src/View/Components/Collapse.php
- Accordion uses the same style as the collapse component, but it works with radio inputs. You can control which item to be open by checking/unchecking the hidden radio input.
- All radio inputs with the same name work together and only one of them can be open at a time. If you have more than one set of accordion items on a page, use different names for the radio inputs on each set.
```
<x-collapse>
<x-slot:heading>
Hello World
</x-slot:heading>
<x-slot:content>
Lorem ipsum dolor sit amet, consectetur adipiscing elit
</x-slot:content>
</x-collapse>
```
Options:
- **accordion-item**: (attr) Defines if the element is part of an accordion group.
- **name**: (attr="value") The name of the radio group if part of an accordion.
- **checked**: (attr) Whether the component is checked by default or …
=> Accordion/Collapse: New components 

src/View/Components/Tags.php
Make "next" button act as "go" on Android devices.
=> Tags: fix Android "next" button

src/View/Components/Input.php
This PR adds the ability to customise the key used in the error bag, this helps with compatibility with Jetstream and other packages. It is backwards compatible with current usage.
Usage Example
```html
<x-mary-input label="{{ __('iam::profile.password.fields.new_password') }}"
type="password"
name="password"
wire:model="state.password"
autocomplete="new-password"
error-bag="password"
/>
```
If you look at how the Jetstream livewire component works, they have a state array which contains most of the fields. The result is the passed as an array to an action which can raise a standard Validation error. The end result of this is the key in the error bag does not have "state" in it, but the wire:model does.
It is preferable to just update the published view template that Jetstream uses, …
=> Input: flexible error bag key

config/mary.php, src/View/Components/Icon.php
Add support to adjust/replace the hardcoded `heroicon` inside the Icon component to allow dot-less naming for non heroicons
=> Icon: add icon set config option

src/View/Components/Choices.php
This pull request introduces the ability to pass additional arguments to the search function used within the `x-choices` component.
**Existing code with the original search-function behavior continues to work seamlessly.**
The `x-choices` component currently allows specifying a search function name only. This function is called with only the search value as the argument.
This PR modifies the x-choices component to accept additional arguments to be passed to the search function. This enables developers to provide more context to the search.
Example:
```html
<x-choices
label="My choices component"
wire:model="selectedItems"
:options="options"
search-function="search('{{$myValue}}', {{$someId}})"
no-result-text="Nothing found!"
searchable
/>
```
This will allow the parent component to handle …
=> feat(choices): Allow passing arguments to search function

src/View/Components/Tab.php
This PR solves #342 by providing a slot for label, in which the programmer can add a badge, such as:
```html
<x-tab name="friends" icon="o-users">
<x-slot:label>
Online Friends
<x-badge class="badge-success text-base-100" value="{{$friends->count()}}"/>
</x-slot:label>
</x-tab>
```
=> Add a slot for a label in the tab component

src/View/Components/Main.php, src/View/Components/MenuItem.php, src/View/Components/ThemeToggle.php
Hi!
I added default theme based on system preferences on alpine present plugin.
Don't why there is 2 params as $light and $dark that i don't see used anywhere.
For route param, this simply fixes my use case, where i have whole user panel under same prefix, and it makes few menu items active at the same time, simply using laravel based request()->routeIs() with * sign you can make only few route available.
Third thing is that i changed classes for sidebar to make it without scroll on sidebar. That the only thing that I'm not 100% sure of. But from my testing everything works great, even with bigger menus.
=> Menu item route param, default theme based on system preferences

src/MaryServiceProvider.php, src/View/Components/MenuTitle.php
I've added a new component MenuTitle & removed the title from MenuSeparator.
I've removed your default uppercase class to comply with daisyUI default style and it's hard to remove it if you don't want it (like me).
Example Images from maryUI-Docs - Left (modified) / Right (current)
In my use-case it looks like that
Dropdown with a simple MenuTitle and a single MenuSeparator
P.S.: mary-ui.com change/PR is coming too ;)
=> MenuTitle: new component & MenuSeparator: remove title and set correct style 

src/View/Components/ThemeToggle.php
This PR allows you to use other themes than the dark and light ones.
Example: 
```
<x-theme-toggle darkTheme="sunset" lightTheme="nord" class="hidden" />
```
=> Allow dark and light theme customization

src/View/Components/Collapse.php
By default, the daisyUI structure for Accordion uses radio. So, at least one item should be selected.
We are changing this to allow to collapse all items.
=> Accordion: allow to collapse all

src/View/Components/Calendar.php
This allows a cleaner way to make the calendar start on Sunday.
Currently to display make the calendar start on Sunday you have to do this
```blade
<x-mary-calendar locale="en-PH" :events="$events" weekend-highlight :config="['settings' => ['iso8601' => false]]" />
```
which IMO pretty verbose for a simple modification.
=> feat: add `sunday-start` modifier

src/MaryServiceProvider.php, src/View/Components/GroupedSelect.php
This introduces a new component `grouped-select` a modified version of the `select` component, this changes only the parsing of the `$option` property. However, unlike `select` which works out of the box for `Eloquent Collections`, this one requires some pre-processing, currently it works like this:
```blade
@php
$grouped_users = [
'Admins' => [['id' => 1, 'name' => 'Mary'], ['id' => 2, 'name' => 'Giovanna'], ['id' => 3, 'name' => 'Marina']],
'Users' => [['id' => 4, 'name' => 'John'], ['id' => 5, 'name' => 'Doe'], ['id' => 6, 'name' => 'Jane']],
];
@endphp
<x-grouped-select label="Group Select Demo" icon="o-user-group" :options="$grouped_users" wire:model="selectedUser" />
```
on my machine it looks like this:
This is an attempt to implement #408
=> SelectGroup: new component

src/View/Components/ImageLibrary.php
When an error occurs while saving the crop the progress is not resetted so the component becomes unusable. By entering this small piece of code the error is displayed and you can continue using the component. To replicate the mistake: trying a crop on a large image with a size close to the upload limit threshold (the crop library produces a blob with a larger size than the original file)
=> Fix ImageLibrary block on crop error

src/View/Components/Form.php
Default : $noseparator false (as now). 
If true, does not display hr above actions.
=> Form : Add $noseparator

src/MaryServiceProvider.php, src/View/Components/Table.php
Closes #466 
Breaking change, for good.
**BEFORE** (`$this->loop->index`)
```blade
<x-table ...>
@scope('cell_name', $user)
({{  $this->loop->index }}) {{ $user->name }}
@endscope
</x-table>
```
**AFTER** (`$loop->index`)
```blade
<x-table ...>
@scope('cell_name', $user)
({{  $loop->index }}) {{ $user->name }}
@endscope
</x-table>
```
=> Table: add `$loop` to `@scope` (breaking change)

src/View/Components/Select.php
Currently `<x-select>` seems to only work with simple arrays.
If we tried passing in an Enum
```html
@php
$statusOptions = \App\Enums\PostStatus::cases();
@endphp
<x-select label="Status" :options="$statusOptions" wire:model="status" />
```
We would get the following error
```
Cannot use object of type App\Enums\PostStatus as array
```
=> Select : allow Enums

src/View/Components/MenuSub.php
Allow sub menus to default to an 'open' state by providing an optional parameter to the component constructor.
=> MenuSub: add 'open' parameter

src/View/Components/Table.php
Closes #500, Closes #479 
- Conditionally render json row if `@row-click` is present.
- Handle string as `selectable-key`
=> Table: improvements

src/View/Components/MenuItem.php, src/View/Components/MenuSub.php
The 'enabled' property has been introduced into the MenuSub and MenuItem components. The render function in both components is now also checking this 'enabled' property. If a component is not enabled, it will now return an empty string and thus not render. This provides more flexibility when controlling the visibility of the components.
We can easily put an `if` before the menu-item but this way it is more manageable for the user
```php
<?php
return [
'main' => [
[
'title'       => 'Dashboard',
'description' => 'Go to dashboard',
'icon'        => 'o-chart-pie',
'link'        => '/',
],
[
'title'       => 'Tasks',
'icon'        => 'o-tag',
'description' => 'Manage tasks',
'link'        => '/tasks',
],
[
'type' => 'separator',
],
[
'title' => 'Settings',
'icon'  => 'o-wrench-screwdriver', …
```
=> Add 'enabled' property to MenuSub and MenuItem components

src/MaryServiceProvider.php, src/View/Components/Pagination.php, src/View/Components/Table.php
A new Pagination component has been created and added to the MaryServiceProvider. This component has been integrated into the Table component to manage table pagination. The addition of Pagination provides greater control and customization options for page number displays. This update also reduces complexity within the Table component by offloading pagination responsibilities.
Enable pagination outside table and add perPage parameter:
```php
class ListTasks extends Component
{
use Toast;
use WithPagination;
use ResetsPaginationWhenPropsChanges;
#[Url]
public string $name = '';
#[Url]
public array $sortBy = ['column' => 'id', 'direction' => 'asc'];
#[Url]
public int $perPage = 10;
public function render()
{
return view('livewire.tasks.list-tasks')->with(
[
'tasks'   => $this->tasks(), …
```
=> Add Pagination component and integrate into Table component

src/View/Components/Dropdown.php
When there are a lot of Dropdown components side by side, the performance is very slow due to x-anchor
For this reason, we added the "no-x-anchor" property.
However, since there are cases where the menu expanded on the screen is filled up, we also added the "top" property.
```php
<x-dropdown no-x-anchor top>
....
```
=> DropdownComponent add new parameter "no-x-anchor" and "top"

src/View/Components/Main.php
=> Sidebar: add `right` and `right-mobile`

src/View/Components/Table.php
empty() doesn't work if $rows is a Paginator
=> Fix empty $rows validation

src/View/Components/Checkbox.php, src/View/Components/Choices.php, src/View/Components/ChoicesOffline.php, src/View/Components/Collapse.php, src/View/Components/DatePicker.php, src/View/Components/Editor.php, src/View/Components/ImageLibrary.php, src/View/Components/Markdown.php, src/View/Components/Pin.php, src/View/Components/Radio.php, src/View/Components/Range.php, src/View/Components/Table.php, src/View/Components/Textarea.php, src/View/Components/ThemeToggle.php, src/View/Components/Toggle.php
Closes #454 
- Adds `label for="xxx"` and `id` whenever  it is possible, because some components does not have a visible "input" associated with its "label". 
- In some cases `<label for="xxx">` was replaced for `<div>`.
**Needs help** from community to check if something is broken. Despite the branch's name, all the components from this PR must be checked.
```
composer require robsontenorio/mary:dev-main-toggle
php artisan view:clear
```
=> Draft: Add label's `for` attribute and missing  `ids`

src/View/Components/Drawer.php
Update Drawer component to properly check modelName value for binding. This ensures the drawer functionality correctly reflects the model's state, improving reliability and accuracy.
Fix when not using model binding:
```blade
<x-drawer id="asdf" title="asdf" separator class="w-11/12 lg:w-1/3 bg-primary !text-white" right>
```
```html
.entangle('')   
```
=> Fix Drawer component binding condition

src/View/Components/Colorpicker.php
Currently the color input of the Colorpicker has no focus styles. There is no feedback on whether it is focused or not.
This pull request adds the focus styles a primary input has.
=> Colorpicker: add focus outline for input with type color

src/View/Components/Textarea.php
Currently when clicking the label of a textarea that has an id it will not focus the associated input. 
This pull request fixes the issue by using the same logic as the Input.php component.
=> Textarea: fix duplicated html id when using nested models.

src/View/Components/MenuItem.php
The `exact` attribute requires the link and route to match exactly in order to show as active in a menu.
This leaves the default functionality of fuzzy-ish matching parent routes, but also avoids issues with numeric IDs unintentionally matching (e.g. ID # 1 and ID # 11 should not match).
Example usage:
```
<x-menu-item title="{{ __('Transactions') }}" icon="o-banknotes" link="####" exact />
//                                                                             ^
```
Ref: #549
=> MenuItem: Adds optional `exact`  attribute on menu items

src/View/Components/File.php
Resolves #575 
Using `#` as `src` in an `img` element downloads the page.
It is a good placeholder for `a:href`, not `img:src`.
=> Remove # default src in crop modal

src/View/Components/Editor.php, src/View/Components/Markdown.php
Add refreshEditor method to Editor component
Introduce a new `refreshEditor` method in the Editor component and enhance the editor initialization with a watcher for content updates, ensuring synchronization between the editor content and the Livewire model. This update improves the component's reactivity and handling of dynamic content changes.
=> Editor/Markdow: allow to change contents on the fly

src/View/Components/Table.php
Hi,
at moment it is not possible to use uuid or strings as expandable key.
With this fix the problem should be fixed.
best regards
Fabian
=> Allow UUIDs and other string as expandableKey

src/View/Components/Table.php
I added an option in table headers to disable the global link from `<x-table link="/my-link" >` for a given column, useful when you want a column to have a custom link via `@scope('cell_.....')` 
To use it you just add the `'disableLink' => true` attribute to your header like this :
```php
public function headers(): array
{
return [
['key' => 'id', 'label' => '#', 'class' => 'hidden lg:table-cell'],
['key' => 'name', 'label' => 'Permission', 'sortBy' => 'name', 'disableLink' => true] , // <--- here
['key' => 'description', 'label' => 'Description', 'sortBy' => 'description'],
];
}
```
=> Table: Added an option to disable link in a given column via 'disable-link' header

src/View/Components/MenuItem.php
When a <x-menu-item/> is created without a tittle, an empty div is rendered.
Fix
=> MenuItems: handle no title 

src/View/Components/File.php
Fixes #603 and resolves #568 by providing the info required by Livewire. As newer version of Livewire use `getClientOriginalExtension` and `pathinfo` within said call, a file name is required in some configuration.
ref. https://github.com/livewire/livewire/commit/70503b79f5db75a1eac9bf55826038a6ee5a16d5
=> File: add a filename to the cropped image on save.

src/View/Components/Table.php
- Fixed issue with zebra striping not being applied to `table` when rows are `expandable`.
- Updated `nth-child` selectors to correctly handle every `4th` and `3rd` rows.
- Resolved conflicts between hover states and expanded rows using dynamic `::class` and `class` bindings.
MaryUI version: `^1.20`
Livewire version: `^3.5`
- Chrome
- Firefox
- Safari
- Edge
- Zebra Striping Issue: Rows with the expandable feature were affected by zebra striping, causing inconsistent row styling, particularly on hover.
https://github.com/user-attachments/assets/e69466ef-bd36-46ce-b7c2-0f1330765cd7
=> Table: allow striped + expandable

src/View/Components/Table.php
- Fixes Issue #512 and other wire:model modifiers.
- Fixes "Undefined method 'pluck'" on ArrayAccess by converting to Collection.
- Fixes "Nested ternary expressions (without parentheses) deprecated in PHP 7.4. Targeting PHP 8.3.0." by wrapping in parentheses.
=> Table: fix wire model modifiers like wire:model.live

src/MaryServiceProvider.php
This fixes the Issue of scope directive throwing an exception with Blade::stringable configuration being present in AppServiceProvider.
https://github.com/robsontenorio/mary/issues/616
=> Fix missing $__bladeCompiler variable in scope directive

src/View/Components/Checkbox.php
This will add the required symbol after the label if the "required" attribute is provided. This was missing and I noticed it while updating the Toggle component.
=> Checkbox: add required symbol if given

src/MaryServiceProvider.php, src/View/Components/Password.php
This will add a new component called Password, closes #552.
I have made the component by copying the Input component, then removing all options that are not relevant and adding a button that can toggle the input type between 'password' and 'text'. Most of the settings from Input still work and the position & icons of the toggle can be customized.
These options have been removed: 
```php
public ?bool $money = false,
public ?string $locale = 'en-US',
```
The new options related to passwords are:
```php
public ?string $passwordIcon = 'o-lock-closed',
public ?string $passwordVisibleIcon = 'o-lock-open',
public ?bool $right = false,
public ?bool $onlyPassword = false,
```
Here are some examples of different configurations:
```blade
<x-password hint="Minimal example" wire:model="password1" /> …
```
=> Introduce new component: Password

src/View/Components/MenuItem.php
As per a comment on discord this PR will add support for modifiers on `wire:navigate` like `wire:navigate.hover` to the MenuItem component.
=> MenuItem: add support for modifiers on wire:navigate

src/View/Components/Input.php
As discussed on the official discord server this PR does the following in the Input component:
- Change the nowdoc language from `<<<'HTML'` to `<<<'BLADE'`.
- Change the comment style from `` to `{{-- ... --}}`.
Note: Because the Blade language in newdoc has a problem with alpinejs's `@` directives those should be changed to `x-on:` instead, otherwise this can break the syntax highlighting. This is the same thing as per [alpinejs docs](https://alpinejs.dev/directives/on#shorthand-syntax). Here is a comparison:
=> Input: change nowdoc language to BLADE and replace comments with blade style

src/View/Components/Choices.php, src/View/Components/ChoicesOffline.php
Adds support for providing `placeholder="Some value"` to Choices and ChoicesOffline. Closes #640.
I tried using the placeholder for the input first but that lead to layout issues so I've added an absolute positioned span instead. I tried to make it look as similar as possible to the input placeholder. 
Because this is a complex component it should be tested with different use-cases. I tested it by adding the placeholder to all cases on the mary-ui.com page for choices. The only not so perfect thing I found was that when searching with the Choices component, the placeholder is removed after the debounce, leading it to overlap with the inputted text for 250ms.
=> Choices: add support for placeholders

src/View/Components/MenuItem.php
Reverts robsontenorio/Mary#636
@anfeichtinger Unfortunately I need revert this, because I noticed it breaks the default behavior of menu items that is `wire:navigate`
=> Revert "MenuItem: add support for modifiers on wire:navigate"

src/View/Components/MenuItem.php
`This is my first time contributing to a project, forgive me if I make a mistake, point out the error so I can improve in the future.`
I added support for the **icon on the right**.
I added support for the **spinner** .
When using a Dropdown, for example, and the action takes a few seconds to complete, it is crucial that the user has visual feedback that something is happening.
To obtain the expected result it is necessary to use MenuItem with `wire:click.stop="archive"`
=> MenuItem: adds icon right and spinner

src/View/Components/Table.php
Disable hover effect on rows. Close #635
=> Table: add `no-hover`

src/View/Components/Password.php
Closes #660.
In the component it used `x-button` instead of `x-mary-button`.
=> Password: fix usage of Buttons and Icons with prefix

src/View/Components/Checkbox.php
Closes #643.
> I think we can go like this :
> 
> `$this->uuid = "mary" . md5(serialize($this)). $this->id;`
>
> So, won’t be conflict if others components has the same id.
Allows passing a custom id to the checkbox component so the uuid can be different in case other parameters are the same.
The following component calls:
```blade
<x-checkbox label="X" wire:model="item1" />
<x-checkbox label="X" wire:model="item1" id="test1" />
<x-checkbox label="X" wire:model="item2" id="test2" />
```
Lead to the following uuids (rendered as label so it is easier to show in the example)
Note: Just providing the id will also lead to a completely different hash anyways so maybe we don't even need to append it.
=> Checkbox: allow appending a custom id to the uuid

src/MaryServiceProvider.php, src/View/Components/Swap.php
This will add a new component Swap, built to simplify [daisy-ui's swap functionality](https://daisyui.com/components/swap/).
Currently we only have the theme toggle which is probably the most common use case for swapping, but it is limited to swapping the current theme. With this you can swap any content. Here are some examples:
```blade
{{-- Default works without model and uses theme toggle icons --}}
<x-swap />
{{-- wire:model + custom icons + flip animation + custom size --}}
<x-swap wire:model="rating" true-icon="o-speaker-wave" false-icon="o-speaker-x-mark"
icon-size="h-8 w-8" class="swap-flip" />
{{-- wire:model.live + simple text content (size and color can be customized by using a parent element) --}}
<x-swap wire:model.live="rating" true="ON" false="OFF" />
{{-- Completely custom …
```
=> Swap: introduce as new component

src/View/Components/Table.php
When a table is empty, the SelectAll checkbox is always active.
This commit disables and uncheck SelectAll checkbox for a better UI experience.
Before
After
=> Improve Table Selectable

src/View/Components/Modal.php
Introduce a close button inside the modal box. The button supports both form submissions and live wire updates, depending on the presence of an ID, enhancing the modal's usability and user experience.
=> Add close button to Modal component

src/View/Components/Editor.php
If the developer intends to self-host TinyMCE under the GPL license, they can set the license_key config option to 'gpl'.
With this change, you can add a setting to use a GPL licence by using gpl-licence ="true".
<x-mary-editor wire:model="text" gpl-license="true" label="Description" hint="The full product description" />
=> Use TinyMCE with the GPLv2+ license

src/View/Components/Avatar.php
This allows to use a text placeholder instead of an image:
```blade
<x-avatar placeholder="ZX"/>
```
=> Add avatar placeholder

src/View/Components/Tab.php, src/View/Components/Tabs.php
This pull request adds support for disabling tabs in the x-tabs component, allowing certain tabs to be visually disabled and preventing user interaction.
The code bellow:
```blade
<x-tabs wire:model.live="person">
<x-tab name="np" label="Pessoa Física" icon="o-users" disabled>
...
</x-tab>
<x-tab name="lp" label="Pessoa Jurídica" icon="o-building-office-2">
...
</x-tab>
</x-tabs>
```
will generate this effect:
When click disabled tab, nothing happens.
=> Refactor Tab component to add support for disabling tabs

src/View/Components/Table.php
=> Table: add basic formatters

src/View/Components/Progress.php
When there is a decimal value such as "10.5", the progress bar will be able to assign its decimal fraction to it, instead of considering only the integral part of that number.
=> Progress: support for decimals

src/View/Components/Editor.php
Fix #742
The `id` is dynamic generated, but now it is allowed to pass any `id`.
=> Editor: Allow to pass `id`

src/View/Components/Choices.php, src/View/Components/ChoicesOffline.php
Added an x-cloak directive to the choices option list container so it doesn't flash momentarily on page load.
https://github.com/robsontenorio/mary/issues/745
=> Added x-cloak to choices

src/View/Components/File.php, src/View/Components/ImageLibrary.php
Disable focus trap, once it uses `native` model.
=> File/ImageLibrary: handle focus trap

src/MaryServiceProvider.php, src/View/Components/Breadcrumbs.php
This PR introduces a new component for breadcrumbs 🚀
While the component follows the general HTML structure of daisy-ui, it offers a lot more flexibility and customization. In order to allow that the [breadcrumb classes](https://daisyui.com/components/breadcrumbs/) are not actually used.
A PR for the mary-ui.com page will follow shorty. Here are some examples:
Closes #798
=> Breadcrumbs: introduce as new component

src/View/Components/Password.php
This will fix both:
- the inconsistent spacing of the visibility toggle button by adding a ``-m-1` class.
- activating the hover effect on the toggle button when hovering the input somewhere else.
-  This is done by changing the `label` tags to `div`. Note: I am not sure why we are using two nested `label` tags anyways. Is there an explanation for this? @robsontenorio 
Closes #849
=> Password: fix button spacing and hover effect

src/View/Components/Menu.php, src/View/Components/MenuItem.php, src/View/Components/MenuSeparator.php, src/View/Components/MenuSub.php, src/View/Components/MenuTitle.php
This will add support for custom `ìcon-classes` to the following components:
- Menu
- MenuItem
- MenuSeparator
- MenuSub
- MenuTitle
Also the string in the `render()` method has been changed to BLADE instead of HTML for consistency and better syntax highlighting.
Closes #713
=> All menu components: add `icon-classes` 

src/View/Components/Card.php, src/View/Components/Collapse.php, src/View/Components/Diff.php, src/View/Components/Dropdown.php, src/View/Components/Form.php, src/View/Components/Header.php, src/View/Components/Hr.php, src/View/Components/ImageLibrary.php, src/View/Components/ListItem.php, src/View/Components/Menu.php, src/View/Components/MenuSeparator.php, src/View/Components/Modal.php, src/View/Components/Nav.php, src/View/Components/Pagination.php, src/View/Components/Popover.php, src/View/Components/Signature.php, src/View/Components/Spotlight.php, src/View/Components/Tabs.php
This is an example of how to adhere border sizes to daisy-ui themes. Here is a quick comparison:
Default theme 1px boder:
Custom theme 5px border:
Default theme 1px boder:
Custom theme 5px border:
The theme was changed by adding the following code to app.css
```css
@plugin "daisyui/theme" {
name: light;
--border: 5px;
}
```
I also noticed a slight difference in color in this example. The border uses `border-t-base-content/10` but the table rows use `border-t-base-content/5`, not sure if that is intentional.
Closes #851
=> All components: use daisyUI CSS variable for borders.

src/View/Components/Editor.php
1. Undo/redo actions are not committing to the editor content and require separate event listeners in the editor setup to recognise these actions.
2. The editor receives a dark variant from the 'data-theme' attribute. This works fine if you only use the 'dark' theme name to toggle dark mode, however, it won't work if you use another dark theme name. The solution is to change TinyMCE's 'skin' and 'content_css' settings to accept the 'dark' variant from the 'class' instead of the 'data-theme' attribute.
=> Editor: fix TinyMCE undo/redo actions and dark mode setting

src/View/Components/Header.php
Added the `icon` property to let the user pick an icon for the header, along with an `icon-classes` property to let the user have control of the size, margin, colors, ... of the icon.
Added some flex classes to the title parent `<div>` to align the title and the icon automatically, and wrapped the title content in a `<span>` to add a small margin when there's an icon.
Showcase of the result :
```html
<x-header icon="o-gif" icon-classes="w-8 h-8 text-red-500" title="Hello" subtitle="messing around with the icon" separator progress-indicator>
<x-slot:middle class="!justify-end">
<x-input placeholder="Search..." wire:model.live.debounce="search" clearable icon="o-magnifying-glass" />
</x-slot:middle>
<x-slot:actions>
<x-button label="Filters" @click="$wire.drawer = true" responsive …
```
=> Add icon and icon classes support for Header

src/View/Components/Carousel.php
Added optional variables `autoplay` and `interval` to control the carousel behavior, respectively `false` and `2000`ms by default.
Note: an `autoplay` carousel with too short and `interval` (typically under 100ms but that may depend on the device / browser) may look broken.
Close #878
=> Carousel: Added optional autoplay setting to carousels (#878)

src/View/Components/MenuItem.php
This PR renames the `$enabled` property as `$hidden` for better readability, and adds the `$disabled` property to allow a menu item to be disabled based on the [daisyUI menu disabled class](https://daisyui.com/components/menu/#menu-with-disabled-items).
Showcase of the result :
Code sample :
```blade
<x-menu activate-by-route>
<x-menu-item title="Hello" icon="o-sparkles" link="/" />
<x-menu-sub title="Settings" icon="o-cog-6-tooth">
<x-menu-item :disabled=true title="Wifi" icon="o-wifi" link="####" />
<x-menu-item :hidden=true title="Archives" icon="o-archive-box" link="####" />
</x-menu-sub>
</x-menu>
```
=> MenuItem: Add disabled property and rename enabled as hidden

src/View/Components/Header.php
When a project changes Mary’s default component prefix (e.g. from `<x-*>` to `<x-mary-*>`), the `<x-mary-header>` component still tried to render its leading icon with:
```blade
<x-icon name="{{ $icon }}" … />
```
Because the tag itself wasn’t prefixed, Livewire/Laravel couldn’t resolve the component class and the icon simply disappeared (see issue #896).
File	Change
```
src/View/Components/Header.php	Replace <x-icon …> with <x-mary-icon …>
```
Only a single line is touched; behaviour is otherwise unchanged.
=> Header: use the internal "x-mary-icon" component

src/View/Components/Card.php
Improvements in this commit are:
1. From the original question in issue #848: The title and subtitle will try to fill the full width of the card.<br/>This allows the title and subtitle to be divided into 2 parts (e.g. the title text and an icon), clearly separted from one another by e.g. applying `justify-between` to it.<br/>FYI: I have introduced a `gap-3` (same as the gap applied to the actions slot) between the title/subtitle and the menu. The card looks off without it.
2. From my additional question in issue #848: The actions will also fill the full width of the card. Moreover, the actions slot can now be specified CS `class`es.<br/>This allows to lay them out in distrinct groups too.<br/>Note that unlike the title/subtitle, actions are applied `justify-end`. As a result, …
=> Card: Layout improvements

src/View/Components/Choices.php, src/View/Components/ChoicesOffline.php
Fix #899 
Disabled `<x-choices>` component is no longer clickable & focusable and it can be reactive based on the value provided by the parent livewire component.
=> Choices/ChoicesOffline: handle dynamic `disabled` and `readonly` states

src/View/Components/Table.php
1. Replace existing `o-arrow-small-down` and `o-arrow-small-up` table sort icons with `o-chevron-down` and `o-chevron-up`.
2. Add neutral state for distinguishing which headers are sortable and which are not.
=> Table: change header sort icons and add neutral sort state

src/View/Components/Drawer.php, src/View/Components/Editor.php, src/View/Components/Modal.php
Add 'on-close' event to Modal and Drawer components to enable triggering of custom methods after component has closed. This is also useful to solve Livewire's current rehydration issue after a model has been deleted (refer [issue 900](https://github.com/robsontenorio/mary/issues/900)). 
Example Use:
```blade
<x-modal wire:model="showModal" on-close="someMethod()">
Content...
</x-modal>
```
=> Modal/Drawer: dispatch `close` event

src/View/Components/Input.php
When using the input component with money and locale attributes, it loses the formatting if you use `wire:model.blur`.
```php
<x-input wire:model.blur="money" money locale="pt-BR"/>
```
This PR fixes the problem.
=> Input: handle `.blur` for money

src/View/Components/DatePicker.php
Fix #939
Retrived from #818 . Credits goes to @iurigustavo
=> DatePicker: use locale settings to handle the `range` mode

src/View/Components/Card.php
This tweak allows users to override the {{slot}} div with their own custom classes.
By default, the body-class is null and will work like default, only providing 'grow-1'.
If body-class is specified, ~~the body div will not use 'grow-1' and only use the specified classes.~~ the body div is appended to, including 'grow-1'.
When using the x-card, i've ran into a problem where overflow-y-auto doesn't work when using the {{slot}} of the x-card.  This ended up being the fix.
Thanks for your work on MaryUI!
=> Extend x-card with body-class option.

src/View/Components/Password.php
Following discussions in #953, this PR implements the no-tab-stop parameter for password fields separately.
Closes #942
=> Input: add `password-icon-tabindex`

src/View/Components/Choices.php, src/View/Components/ChoicesOffline.php
Closes #963 
Hello, I have added a fix for the issue in the `Choices` & `Choices Offline` component as mentioned in #963. I used `--size` as the value for min-height instead of the plain `min-h-fit` to define the initial height. Additionally, I added `h-auto` so the height automatically adjusts based on the number of selected choices.
Examples:
**Edge** 
**Firefox**
=> Choices/ChoicesOffline: fix Firefox issue

src/View/Components/Stat.php
added the `truncate` utility class to the description area of the `stat` component to prevent layout overflow on small screens.
Without `truncate`, long descriptions can break the layout or overflow out of the stat box.
=> Stat: fix overflow on small screens

src/View/Components/Spotlight.php
Add a `name` to the input field, so the browser can't autocomplete it.
=> Spotlight: disable browser autocomplete
