src/MaryServiceProvider.php
src/View/Components/Calendar.php
src/View/Components/Choices.php
src/View/Components/ListItem.php

**NEW**
- **Calendar**: display events 
**CHANGES**
- **Select**: allow array syntax
- **ListItem**: allow array syntax

Improvements

---

src/View/Components/Radio.php

Fixed Radio

---

src/View/Components/Table.php

Allow paged data type in rows, like a Paginator, LengthAwarePaginator or CursorPaginator.

allow paged data type in rows

---

readme.md
routes/web.php
src/MaryServiceProvider.php
src/View/Components/Calendar.php
src/View/Components/ListItem.php
src/View/Components/Main.php
src/View/Components/Menu.php
src/View/Components/MenuItem.php
src/View/Components/Nav.php
src/View/Components/Table.php

- **Main**: add `collapsible` parameter on `sidebar` slot and extra web routes to handle toggle.
- **Main**: add `full-wdith` parameter.
- **Nav**: add `full-wdith` parameter.
- **Calendar**: allow `Carbon` instances.
- **ListItem**: add `no-hover` parameter.
- **Menu / MenuItem**: add `activate-by-route` parameter 
- **Menu**: add `activate-bg-color` parameter 
- **Table**: Allow arrays

Sidebar and fixes

---

src/Console/Commands/MaryInstallCommand.php
src/MaryServiceProvider.php
stubs/Welcome.php
stubs/app.blade.php
stubs/app.css
stubs/tailwind.config.js
stubs/web.php

INSTALLER: add automatic installer

---

src/View/Components/Radio.php

RADIO: allow array syntax

---

src/MaryServiceProvider.php
src/View/Components/TimelineItem.php

TIMELINE: add timeline component

---

src/View/Components/MenuItem.php

MENU: allow named routes for MenuItem activation

---

src/View/Components/TimelineItem.php

Timeline: small CSS fix

---

src/View/Components/Main.php

```html
<x-main>
<x-slot:sidebar collapsible collapse-text="Hide it">
.....
</x-slot:sidebar>
</x-main>
```

Main: expose sidebar slot attribute `collapse-text`

---

src/View/Components/Header.php
src/View/Components/Modal.php

Modal: fix spacing when using header

---

src/View/Components/Textarea.php

- Removed Extra Top Padding class
- Fixed Textarea Class

Textarea: fix CSS

---

src/View/Components/Select.php

Example
```php
<x-select label="Type" icon="o-user" :options="[
['id' => 'trending', 'name' => 'Trending Content','disabled'=>true],
['id' => 'latest', 'name' => 'Latest Content'],
['id' => 'information', 'name' => 'Information Content'],
]"
wire:model="type" />
```

Select: allow disable options

---

src/Traits/Toast.php

Add toast flash messages for make testing easier.
```php
->assertSessionHas('mary.toast.title', 'Something get wrong');
->assertSessionHas('mary.toast.description', 'Please, check logs');
```

Toast: add convenience flash messages

---

src/View/Components/Tab.php

Fixes #51 
Workaround due to teleport issue when re-rendering component.

Tab: fix when re-render component

---

.gitignore

Env: ignore `.idea/` directory

---

src/Facades/Mary.php

Solves #56 
Fix facade namespace.

IDE helper: fix facade namespace

---

src/Traits/Toast.php
src/View/Components/Toast.php

Use daisyUI classes `toast-xxxx` instead of `top-10 bottom-10 ....`

Toast: proper use daisyUI classes.

---

src/View/Components/Button.php

Button: add tooltips

---

src/View/Components/Table.php

Table: allow to override nested header `key`

---

src/View/Components/Header.php

```
<x-header title="Mary components" with-anchor />
```
Outputs
```html
<div class="text-2xl font-extrabold mary-header-anchor" id="mary-components">
<a href="#mary-components">
Mary components
</a>
</div>
```

Header: add `with-anchor` attribute.

---

composer.json
composer.lock
src/Console/Commands/MaryInstallCommand.php
stubs/app.blade.php

- Remove TTY
- Yarn or Npm?
- Install Livewire/Volt?
- Check for starter kits
- Check for composer.json and package.json
- Check for stubs

Installer: improve with validations

---

src/View/Components/Icon.php

Icon: allow another iconset

---

src/View/Components/Table.php

Table: add `expandable` and `selectable`

---

src/View/Components/Nav.php

Nav: fix `actions` slot gap

---

src/View/Components/Header.php

Header: add `progress-indicator`

---

src/View/Components/Menu.php
src/View/Components/MenuItem.php

MenuItem: add `badge` attribute

---

src/View/Components/Button.php

Button: add `link` and `external` properties

---

src/View/Components/Header.php

Fix anchor position on html hierarchy.

Header: fix `anchor` semantic

---

src/MaryServiceProvider.php
src/View/Components/File.php

File: simple uploads

---

src/View/Components/Input.php

Input: Add inputmode numeric for `money`

---

src/View/Components/Table.php
stubs/tailwind.config.js

Table: add rows `link`

---

src/View/Components/DatePicker.php
src/View/Components/DateTime.php
src/View/Components/Input.php
src/View/Components/Select.php
src/View/Components/Textarea.php

Readonly: fix readonly attribute for all inputs.

---

src/View/Components/Textarea.php

Textarea: add default `$slot`

---

src/View/Components/Select.php

Fixes #10 
Default is `null` if omitted.

Select: add `placeholder-value`

---

src/View/Components/DatePicker.php
src/View/Components/DateTime.php

- Field appearance
- Pointer event

Datetime / Datepicker: fix IOS

---

src/View/Components/MenuItem.php

Solve a route issue when `link="/"`.

MenuItem: fix route

---

src/View/Components/Button.php
src/View/Components/Stat.php
stubs/app.blade.php

- Stat: add `tooltip`
- Stat/Button: show only `md:` and up

Tooltip: improvements

---

src/View/Components/Table.php

Add `wire:key` to make Livewire happy.

Table: add `wire:key`

---

src/MaryServiceProvider.php
src/View/Components/Chart.php

Chat: add third-party chart component

---

src/View/Components/Choices.php
src/View/Components/Table.php

Weird random issue when using `@js`.

Fix: use `json_encode` instead `@js`

---

config/mary.php
src/MaryServiceProvider.php

Add config for prefix component's name.
```php
?php
return [
/**
* Default is empty.
*    prefix => ''
*              <x-button />
*              <x-card />
*
* Renaming all components:
*    prefix => 'mary-'
*               <x-mary-button />
*               <x-mary-card />
*/
'prefix' => ''
];
```

Draft: Introduce component renaming

---

src/Console/Commands/MaryInstallCommand.php

Installer: add missing volt install command

---

src/View/Components/ListItem.php

ListItem: Fix `wire:key` uniqueness

---

stubs/app.blade.php

Avoid zoom on some fields on mobile.

Stub: better viewport example

---

src/View/Components/Header.php

- Allow classes for `title`, `subtitle` and `actions` slots.

Header: Improvements

---

src/View/Components/Card.php

- Allow custom `wire:key`
- Allow classes for `title` and `subtitle` slots.

Card: Improvements

---

src/View/Components/Toast.php

Fixes #122 
- It does not play well here.
- The transtion was useless.

Toast: remove useless transition

---

src/View/Components/Tab.php
src/View/Components/Tabs.php

- Allow to use css classes as attributes.
- Remove unused method.

Tabs: css attributes

---

src/MaryServiceProvider.php
src/View/Components/Avatar.php

Avatar: new component

---

src/View/Components/Tab.php
src/View/Components/Tabs.php

- Correctly support `wire:model.live`

Tab: fix model entangle

---

src/View/Components/Modal.php

Fix: Close button modal backdrop

Fix: Close button modal backdrop

---

src/View/Components/MenuItem.php

External link enable on `MenuItem` component

MenuItem : Add `external` attribute for links

---

src/View/Components/Choices.php

Design Improvements: Choices Component

Choices: fix word breaks

---

src/View/Components/Main.php
src/View/Components/Nav.php

Main/Sidebar: Improvements

---

src/View/Components/Dropdown.php
src/View/Components/MenuItem.php

- Use new x-anchor from Alpine for auto positioning 
- MenuItem: improve clickable area

Dropdown: use Alpine `x-anchor` / MenuItem: improve clickable area

---

src/View/Components/Button.php

Button: fix `link` + `tooltip` combined

---

src/View/Components/Button.php

- Responsive: hide `label` on `xs`, display on `lg`
- Badge: add badge on right side

Button: `responsive` and `badge`

---

src/View/Components/Tabs.php
src/View/Components/TimelineItem.php

- Timeline with icons
- Tab classes

Upgrade for daisyUI4

---

src/View/Components/Checkbox.php
src/View/Components/Toggle.php

Fixes #174  #175 
- Checkbox: add validation
- Checkbox/Toggle: add `hint` attribute

Checkbox/Toggle: improvements

---

src/View/Components/Button.php

Button: add `no-wire-navigate` attribute

---

src/MaryServiceProvider.php
src/View/Components/Errors.php
src/View/Components/Input.php

Errors: new component

---

src/View/Components/Choices.php

Fix #178 
Fix case where string starts with ZERO.

Choices: fix numeric/string

---

src/View/Components/Choices.php

Choices: add `prepend` and `append` slots

---

src/View/Components/Radio.php

- Add missing `div` for better auto alignment when using forms.

Radio: wrapper div

---

src/View/Components/Table.php

Table: Pagination

---

src/View/Components/Table.php

Table: sortable

---

src/View/Components/MenuSub.php

Fix #201 
- Add `@click.stop` to make it work nice with Dropdowns

MenuSub: fixes

---

src/View/Components/Choices.php
src/View/Components/ChoicesOffline.php

- Use Alpine anchor for vertical auto positioning.
- Handle search input hide.

Choices/ChoicesOffline: improvements

---

src/View/Components/Choices.php
src/View/Components/ChoicesOffline.php
src/View/Components/DatePicker.php
src/View/Components/DateTime.php
src/View/Components/Input.php
src/View/Components/Radio.php
src/View/Components/Select.php
src/View/Components/Tags.php
src/View/Components/Textarea.php

```html
<x-input label="Name" wire:model="name" required />
```

All inputs: add required label `mark`

---

src/View/Components/Input.php

Input: add `clearable` property

---

src/Console/Commands/MaryInstallCommand.php

This PR will fix the issues with windows 
I've updated the `copyStubs` function to work smoothly on both Windows and Unix-based systems. Now, it cleverly uses PHP's own tools to handle files and folders, making sure everything runs without a hitch no matter the platform. Plus, I've added some smart checks to avoid any mix-ups with already existing directories.

Fix cross-platform compatibility for `copyStubs`

---

config/mary.php
routes/web.php
src/MaryServiceProvider.php
src/View/Components/Spotlight.php

Spotlight: new component

---

src/View/Components/Choices.php
src/View/Components/ChoicesOffline.php

Choices/ChoicesOffline: Fix `required`

---

composer.json
src/Console/Commands/MaryInstallCommand.php
src/View/Components/Main.php
stubs/AppBrand.php
stubs/Welcome.php
stubs/app.blade.php
stubs/welcome.blade.php

- Adds a nice starter example with working code.

Onboarding: better Hello World

---

src/View/Components/ListItem.php

Fix: avatar links in ListItem (#232)

---

src/View/Components/Table.php

Add an ability to set a `sortBy` value per column on `$headers`

Table: custom sortBy per column

---

src/View/Components/ChoicesOffline.php

There was some glitch with Alpine approach. Now it uses blade.

Choices: ditch from `Alpine` and use `blade`

---

src/View/Components/Tab.php
src/View/Components/Tabs.php

Fix #243 
- Ditch from teleport approach

Tabs: fix `slot`

---

src/MaryServiceProvider.php
src/Traits/WithMediaSync.php
src/View/Components/File.php
src/View/Components/ImageLibrary.php

- Add new component **ImageLibrary**
- Update File component for single image preview/crop.

File image preview/crop + Image Library

---

src/MaryServiceProvider.php
src/View/Components/ThemeToggle.php

ThemeToggle: new component

---

src/MaryServiceProvider.php
src/View/Components/Step.php
src/View/Components/Steps.php

Steps: new component

---

src/View/Components/Tabs.php

Fix weird issue with Alpine when clicking browser back button.

Tabs: fix navigate back

---

src/MaryServiceProvider.php
src/View/Components/ImageGallery.php

A companion for ImageLibrary component.

ImageGallery: new component

---

src/Traits/WithMediaSync.php
src/View/Components/ImageGallery.php
src/View/Components/ImageLibrary.php

ImageLibrary: add `disk` option

---

src/View/Components/ThemeToggle.php

Use native Tailwind dark mode support

ThemeToggle: fix native Tailwind support

---

src/View/Components/Tab.php
src/View/Components/ThemeToggle.php

Fix #265 
Add no wrap to tab labels.

Tabs: fix label

---

routes/web.php
src/MaryServiceProvider.php
src/View/Components/Editor.php

Editor: new component

---

src/Traits/WithMediaSync.php

ImageLibrary: fix file extension

---

src/View/Components/Tab.php

Tab: allow dynamic remove tabs

---

src/View/Components/Step.php
src/View/Components/Steps.php

Steps: improvements

---

src/View/Components/Modal.php

Modal: conditional render slot `actions`

---

src/View/Components/File.php

Fixes: #283 
Uses `x-mary-button`

File: fix button

---

src/View/Components/Tags.php

Fix #288 #277
- Add `tab` as hotkey to address Android behavior.
- Improve CSS to fix space issue when not focused
- Add array model validation.

Tags: fixes

---

src/MaryServiceProvider.php
src/View/Components/Kbd.php

**Kbd** is used to display keyboard shortcuts.
Usage:
```
<x-kbd>F</x-kbd>
```
Customizing Sizes:
Add `kbd-xs` | `kbd-sm` | `kbd-md` | `kbd-lg` to the class attribute. For example:
```
<x-kbd class="kbd-lg">F</x-kbd>
```

KBD: New Component

---

src/View/Components/ImageLibrary.php
src/View/Components/Spotlight.php

Hi, 
two minor tweaks to fix issues I found while using the library, thanks for the hard work!
Correct Spotlight.php component to use x-mary-model
Correct ImageLibrary.php component to use x-mary-button

Correct components to use internal x-mary- components

---

src/MaryServiceProvider.php
src/View/Components/Range.php

**Range** slider is used to select a value by sliding a handle.
Usage:
```
<x-range
wire:model="dataRange" // Binds the component to a Livewire model.
min="0" // Optional: Specifies the minimum value. Defaults to 0 if not provided.
max="100" // Optional: Specifies the maximum value. Defaults to 100 if not provided.
step="10" // Optional: Defines the step size between values.
class="range-accent" // Allows customization of the slider's color or size.
label="Select a price range" // Optional: Displays a label for the slider.
hint="This is the range hint" // Optional: Provides additional information or guidance.
required // Marks the slider as required for form submission.
/>
```
Available Sizes:
`range-xs` | `range-sm` | `range-md` (default) | `range-lg`
<hr />

Range: New Component

---

src/View/Components/ImageGallery.php

Improve the way width/height are set.

ImageGallery: Better dimensions

---

src/View/Components/Toast.php

Toast: mobile CSS

---

src/MaryServiceProvider.php
src/View/Components/Markdown.php

Markdown: new component.

---

src/View/Components/Markdown.php

- Upload state
- Lifecycle control (destroy)

Markdown: improvements

---

src/Console/Commands/MaryInstallCommand.php
src/View/Components/Main.php
stubs/app.blade.php

Try another approach for better positioning `collapse` button

WIP: Sidebar: better `collapse`

---

src/View/Components/Avatar.php
src/View/Components/Dropdown.php
src/View/Components/Main.php
stubs/app.blade.php

Hello,
I've got another tweak I hope you will consider. When using the dropdowns with the trigger slot, it would be nice to be able to customise the classes which are applied to the summary.

Dropdown classes on slot

---

config/mary.php
src/View/Components/Icon.php

Reverts robsontenorio/mary#345

Revert "Icon: add icon set config option"

---

src/MaryServiceProvider.php
src/View/Components/Colorpicker.php

ColorPicker: new component

---

src/MaryServiceProvider.php
src/View/Components/Pin.php

PIN: new component.

---

src/View/Components/Colorpicker.php

Make it clickable on mobile IOS.

Colorpicker: fix mobile IOS

---

src/MaryServiceProvider.php
src/View/Components/Signature.php

Signature: new component

---

src/Console/Commands/MaryInstallCommand.php

Add bun as package installer

---

src/Console/Commands/MaryInstallCommand.php

This PR adds `pnpm` as an option to the installation command.
There are no breaking changes to this pr

Add PNPM to install command

---

src/View/Components/DatePicker.php

Datepicker: add support for plugins

---

src/View/Components/Alert.php

Alert: fix close button.

---

src/View/Components/DatePicker.php
src/View/Components/Input.php

Closes #418 
this PR fixed indexed nested array model problem in Date Picker and Input(money) components

fix indexed nested array model

---

src/View/Components/DatePicker.php
src/View/Components/Input.php

Reverts robsontenorio/mary#421

Revert "fix indexed nested array model"

---

src/View/Components/Stat.php

This PR will handle the RTL support for the Stat component if html dir is set to `rtl`

Statistic: RTL support

---

src/View/Components/Table.php

Table: fix selectable (checkbox)

---

src/View/Components/Collapse.php

Collapse: add `no-icon` option

---

src/MaryServiceProvider.php
src/View/Components/Popover.php

Popover: new component

---

src/View/Components/Editor.php

Closes #463 #464 
Also add `change` event.

Editor: fix update

---

src/MaryServiceProvider.php

The aim is to optimize the code and automate the integration of a new component by simply creating the class.

MaryServiceProvider update

---

src/MaryServiceProvider.php

Reverts robsontenorio/Mary#469

Revert "MaryServiceProvider update"

---

src/View/Components/Tabs.php

I added the ability for devs to customize the tabs component to there use case. I will add update to the docs next

Tabs: to allow full external customisation

---

config/mary.php
routes/web.php
src/View/Components/Editor.php
src/View/Components/Main.php
src/View/Components/Markdown.php
src/View/Components/Spotlight.php

Hello,
I have a specific case where I need to prefix all my routes. That's the reason I'm proposing those changes, including naming the routes.

Set names and allow prefix routes

---

src/View/Components/Rating.php

Rating: fix default color

---

src/View/Components/Rating.php

Rating: allow `zero`

---

src/MaryServiceProvider.php
src/View/Components/Carousel.php

It adds the carousel component from daisyui. This can be useful because it simplifies the creation of the component.
This adds basically three types of carousel, ***basic***, ***withArrows*** and ***withIndicators***
The other smalls customization like vertical and the Full-bleed carousel can be applied just by adding its classes.
The component needs a string array with the images URLs.
```php
public array $images = [
"https://images.unsplash.com/photo-1637077147282-afe85012f74d?ixid=M3wxMTI1OHwwfDF8cmFuZG9tfHx8fHx8fHx8MTcxODgwNTE0N3w&ixlib=rb-4.0.3&q=85&w=1920",
"https://images.unsplash.com/photo-1590425524758-2efb3f31eae2?ixid=M3wxMTI1OHwwfDF8cmFuZG9tfHx8fHx8fHx8MTcxODgwNTE0N3w&ixlib=rb-4.0.3&q=85&w=1920",
"https://images.unsplash.com/photo-1598638077897-d987bbf4f348?ixid=M3wxMTI1OHwwfDF …
```

Carousel: new component

---

src/View/Components/Choices.php
src/View/Components/ChoicesOffline.php
src/View/Components/Colorpicker.php
src/View/Components/DatePicker.php
src/View/Components/DateTime.php
src/View/Components/Editor.php
src/View/Components/Errors.php
src/View/Components/File.php
src/View/Components/ImageLibrary.php
src/View/Components/Input.php
src/View/Components/Markdown.php
src/View/Components/Radio.php
src/View/Components/Select.php
src/View/Components/SelectGroup.php
src/View/Components/Signature.php
src/View/Components/Tab.php
src/View/Components/Table.php
src/View/Components/Tags.php
src/View/Components/Textarea.php
src/View/Components/TimelineItem.php
src/View/Components/Toast.php
stubs/AppBrand.php
stubs/app.blade.php

RTL support based on [Tailwind Simplified RTL support with logical properties](https://tailwindcss.com/blog/tailwindcss-v3-3#simplified-rtl-support-with-logical-properties) post

RTL support

---

src/View/Components/Drawer.php

Add support for Livewire model binding in Drawer component

---

src/View/Components/Table.php

It is possible to add an option to hide columns instead of deleting values ​​in the array headers at certain indexes and returning them back to the original order.

Add hidden column option

---

src/View/Components/Radio.php

Allow an option set to 'disable' an option by defining `disabled === true`

Add 'disabled' option to Radio component options

---

src/View/Components/Drawer.php

Closes https://github.com/robsontenorio/mary/issues/555

Drawer: make x-trap directive on the drawer optional

---

src/View/Components/Editor.php

Closes #554 
Add extra disambiguation step for UUID.

Editor: fix UUID

---

src/View/Components/Choices.php

Remove ID from Component.
Closes #569 #563

Choices: fix blank

---

src/View/Components/Checkbox.php
src/View/Components/Choices.php
src/View/Components/ChoicesOffline.php
src/View/Components/Colorpicker.php
src/View/Components/DatePicker.php
src/View/Components/DateTime.php
src/View/Components/Editor.php
src/View/Components/File.php
src/View/Components/Input.php
src/View/Components/Radio.php
src/View/Components/Range.php
src/View/Components/Select.php
src/View/Components/SelectGroup.php
src/View/Components/Signature.php
src/View/Components/Tags.php
src/View/Components/Textarea.php

Ability to override the default hint classes.

All Fields: allow to customize hint CSS classes

---

src/View/Components/Tab.php

Closes: #565
Handles :
- Add dynamic tabs 
- Properly update the `label` slot content.

Tabs: handle dynamic `label` slot.

---

src/View/Components/ChoicesOffline.php

Replaced static UUID bindings with dynamic ID bindings using Alpine.js in the ChoicesOffline component. This change improves reactivity and ensures accurate element targeting within the component.
refs:
https://github.com/alpinejs/alpine/discussions/2989

Add dynamic ID binding for Choice component

---

src/View/Components/Table.php

Table: allow `route()` for links

---

src/View/Components/Pagination.php
src/View/Components/Table.php

Hide perPage select on empty tables
Before
After

Table: additional condition to display `perPage` selector

---

src/View/Components/Table.php

Table: add property to set classes to table div container

---

src/View/Components/Choices.php

Choices: handle late render

---

src/View/Components/Table.php

add expandable condition boolean to table class
<hr />
Closes #597

Table: add `expandable-condition`

---

src/View/Components/Toggle.php

This will ...
- ...add the required symbol after the label text if the "required" attribute is given.
- ...add validation error messages configurable like on the checkbox component.
Edit: Closes #610

Toggle: add required symbol if given, add validation errors

---

composer.json
composer.lock

Fix Laravel Prompts dependency.

---

src/View/Components/Calendar.php

Hello, 
I found a bug, If there's an event has a same date, it shows only the first event, I am trying to show all event and seperated by 
`<hr>`
I am using foreach, because it takes bit faster than using map, [ref](https://stackoverflow.com/questions/18144782/performance-of-foreach-array-map-with-lambda-and-array-map-with-static-function)

Calendar: allow duplicated dates

---

src/View/Components/Alert.php
src/View/Components/Avatar.php

As experiment, just add API Docs for Alert and Avatar

Add API Docs

---

src/View/Components/Choices.php
src/View/Components/ChoicesOffline.php

Choices/ChoicesOffline: large numbers

---

src/View/Components/ImageLibrary.php

Image library: small css fix

---

src/View/Components/Toggle.php

Toggle: allow to pass `id`

---

src/View/Components/Calendar.php

Calendar: add wire:key

---

src/View/Components/Modal.php

Modal: support RTL

---

src/View/Components/Choices.php
src/View/Components/ChoicesOffline.php

Added addition key exceptions to the choices widget per: https://github.com/robsontenorio/mary/issues/752

M ui752 add keydown exceptions to choices

---

src/View/Components/Signature.php

This commit allows further styling of the `clear button`.

Signature: add clearBtnStyle

---

src/Console/Commands/MaryInstallCommand.php

Lock daisyUI at v4 and tailwind at v3  until we release mary v2.

Installer: lock versions

---

src/View/Components/Modal.php

Modal: add focus trap

---

src/View/Components/Modal.php
src/View/Components/Toast.php

Modal / Toast: increase z-index

---

src/View/Components/Pin.php

This feature allows you to hide the pin

FEATURE | added possibility to hide the pin

---

src/View/Components/Form.php

Form: allow to override `actions` slot

---

src/View/Components/ThemeToggle.php

ThemeToggle: add `class` handle.

---

src/View/Components/Table.php

Add toggleCheckAll event to the table component

Table: add row-selection-all event to table

---

src/View/Components/DatePicker.php

Datepicker: fix live

---

src/View/Components/Main.php

Main: fix height when using `with-nav`

---

src/View/Components/Input.php

Input: fix money for `live` model

---

src/View/Components/Avatar.php

Avatar: add `alt` HTML property.

---

src/View/Components/Tab.php
src/View/Components/Tabs.php

Tabs: add `hidden` state

---

src/View/Components/ChoicesOffline.php

Closes #792
This is a workaround until fix of
https://github.com/alpinejs/alpine/discussions/4390

ChoicesOffline: fix keyboard navigation

---

src/View/Components/DatePicker.php

Datepicker: implement `disable` option

---

src/View/Components/Toast.php

Need go back to this later, after daisyUI fix.
https://github.com/saadeghi/daisyui/issues/3738

Toast: make it responsive

---

src/View/Components/Colorpicker.php

ColorPicker: fix model

---

src/View/Components/Table.php

Stop click propagation.
Fix #877

Table: `@row-selection` click event.

---

src/View/Components/Choices.php
src/View/Components/ChoicesOffline.php

fix #879 
Choice and choice offline badge height 
Preview (Before) :
Preview (After) :
Thank You

Choices/ChoicesOffline: fix badge height #879

---

src/View/Components/Header.php

Header: add `progress-indicator-class`

---

src/View/Components/Icon.php

Icon: apply click events to labels

---

src/View/Components/Signature.php

Signature: fix `clear` action

---

src/View/Components/ListItem.php

This allows to use a fallback image if "avatar" image is not found.

ListItem: add `fallback-avatar`

---

src/View/Components/ListItem.php

Properly utilize the `fallbackAvatar` property.

ListItem: fallback avatar

---

src/View/Components/ListItem.php

ListItem: remove padding from individual elements
